[config]
schemaVersion = "0.0.1"

[package]
namespace = "MT2_Sandscourged"
name = "The_Sandscourged"
versionNumber = "0.3.1"
description = "Adds the Sandscourged clan to Monster Train 2"
websiteUrl = "https://github.com/AidenSheehan/MT2_Sandscourged"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
MT2-Trainworks_Reloaded = "0.5.4"
Conductor-Conductor ="0.2.0"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./"

[[build.copy]]
source = "./plugin_build"
target = ""

[publish]
repository = "https://thunderstore.io"
communities = [ "monster-train-2" ]







