[config]
schemaVersion = "0.0.1"

[package]
namespace = "MT2_Sandscourged"
name = "Sandscourged"
versionNumber = "0.0.1"
description = "Adds the Sandscourged clan to Monster Train 2"
websiteUrl = "https://thunderstore.io"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
MT2-Trainworks_Reloaded = "0.4.0"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./"

[[build.copy]]
source = "./plugin_build"
target = ""

[publish]
repository = "https://thunderstore.io"
communities = [ "monster-train-2" ]


